# global configs
Global:
  checkpoints: null
  pretrained_model: "/workspace/hesensen/DOLG_reprod/PaddleClas/oosd"
  output_dir: "./output_GLDv2/"
  device: "gpu"
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 20
  use_visualdl: False
  eval_mode: "classification_dolg"
  # retrieval_feature_from: "features" # 'backbone' or 'features'
  # re_ranking: False
  # used for static mode and model export
  image_shape: [3, 512, 512]
  save_inference_dir: "./inference"

# model architecture
Arch:
  name: "RecModel"
  infer_output_key: "features"
  infer_add_softmax: False
  Backbone:
    name: "DOLG"
    stage3_channels: 1024
    stage4_channels: &embedding_size 2048
    with_aspp: False
    globalmodel_pretrained: pretrained_model/R-50-1x64d_dds_8gpu
  Neck:
    name: "FC"
    embedding_size: *embedding_size
    class_num: &feat_dim 512
    weight_attr:
      initializer:
        name: KaimingUniform
        fan_in: 12288 # 6*embedding_size
    bias_attr:
      initializer:
        name: KaimingUniform
        fan_in: 12288 # 6*embedding_size
  Head:
    name: "ArcMarginP"
    embedding_size: *feat_dim
    class_num: 81313
    margin: 0.15
    scale: 30.0

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0

  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  use_nesterov: True
  multi_precision: False
  lr:
    name: CustomCosine
    learning_rate: 0.05 # 8gpux8bs
    warmup_epoch: 6
    warmup_factor: 0.1
    by_epoch: True
  regularizer:
    name: "L2"
    coeff: 0.0001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: "LandmarkDataset"
      image_root: "/workspace/dongshuilong/dataset/ppshitu_traindata/GLDv2/"
      cls_label_path: "/workspace/dongshuilong/dataset/ppshitu_traindata/GLDv2/train_list.txt"
      transform_ops:
        - RandomResizeCrop:
            size: 512
            area_frac: 0.08
            max_iter: 10
        - RandFlipImage:
            flip_code: 1
        - ToCHWImage:
        - NormalizeImage: # only scale to [0,1]
            scale: 1.0
            mean: [0.0, 0.0, 0.0]
            std: [255.0, 255.0, 255.0]
            order: "chw"
            output_fp16: False
            channel_num: 3
        - PCAJitter:
            alpha_std: 0.1
            eig_val: [[0.2175, 0.0188, 0.0045]]
            eig_vec:
              [
                [-0.5675, 0.7192, 0.4009],
                [-0.5808, -0.0045, -0.8140],
                [-0.5836, -0.6948, 0.4203],
              ]
        - NormalizeImage: # do color norm(subtract mean and divide std)
            scale: 1.0
            mean: [0.406, 0.456, 0.485]
            std: [0.225, 0.224, 0.229]
            order: "chw"
            output_fp16: False
            channel_num: 3

    sampler:
      name: DistributedBatchSampler
      batch_size: 16 # 128/|gpus(8)|
      drop_last: True
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True
  Eval:
    dataset:
      name: "LandmarkDataset"
      image_root: "/workspace/dongshuilong/dataset/ppshitu_traindata/GLDv2/"
      cls_label_path: "/workspace/dongshuilong/dataset/ppshitu_traindata/GLDv2/val_list.txt"
      transform_ops:
        - ShortScale:
            short_size: 512
            interpolation: "bilinear"
            backend: "cv2"
        - CenterCrop:
            size: 512
        - ToCHWImage:
        - NormalizeImage: # only scale to [0,1]
            scale: 1.0
            mean: [0.0, 0.0, 0.0]
            std: [255.0, 255.0, 255.0]
            order: "chw"
            output_fp16: False
            channel_num: 3
        - NormalizeImage: # do color norm(subtract mean and divide std)
            scale: 1.0
            mean: [0.406, 0.456, 0.485]
            std: [0.225, 0.224, 0.229]
            order: "chw"
            output_fp16: False
            channel_num: 3
    sampler:
      name: DistributedBatchSampler
      batch_size: 8
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True

Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - TopkAcc:
        topk: [1, 5]
