# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output_V1_baseline_small_LCNetV2_base_tweaks_bnneck_tripletanglemargin_samplesampler/
  device: gpu
  save_interval: 110
  eval_during_train: True
  eval_interval: 1
  epochs: 100
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference_V1_baseline_small_LCNetV2_base_tweaks_bnneck_tripletanglemargin_samplesampler
  eval_mode: retrieval
  use_dali: False
  to_static: False

# model architecture
Arch:
  name: RecModel
  infer_output_key: features
  infer_add_softmax: False

  Backbone:
    name: PPLCNetV2_base
    pretrained: True
    use_ssld: True
    use_last_conv: False
    fc_dropout: True
    dropout_prob: 0.2
    class_num: &feat_dim 512
  Neck:
    name: BNNeck
    num_features: *feat_dim
    weight_attr:
      initializer:
        name: Constant
        value: 1.0
    bias_attr:
      initializer:
        name: Constant
        value: 0.0
      learning_rate: 1.0e-20 # NOTE: Temporarily set lr small enough to freeze the bias to zero
  Head:
    name: ArcMargin
    embedding_size: 512
    class_num: 8750
    margin: 0.2
    scale: 30

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
    - TripletAngleMarinLoss:
        weight: 1.0
        margin: 0.5
        reduction: mean
        add_absolute: True
        absolute_loss_weight: 0.2
        normalize_feature: True
        feature_from: "features"
        ap_value: 0.9
        an_value: 0.4
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.04
    warmup_epoch: 5
  regularizer:
    name: "L2"
    coeff: 0.00001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: ./dataset/small_dataset
      cls_label_path: ./dataset/train_reg_all_data_small_no_face.txt
      relabel: True
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ""

    sampler:
      name: PKSampler
      batch_size: 256
      sample_per_id: 4
      drop_last: False
      shuffle: True
      sample_method: "sample_avg_prob"
    loader:
      num_workers: 8
      use_shared_memory: True

  Eval:
    Query:
      dataset:
        name: VeriWild
        image_root: ./dataset/ppshitu_rec_test_white_data/
        cls_label_path: ./dataset/ppshitu_rec_test_white_data/query_clean.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ""
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

    Gallery:
      dataset:
        name: VeriWild
        image_root: ./dataset/ppshitu_rec_test_white_data/
        cls_label_path: ./dataset/ppshitu_rec_test_white_data/gallery_clean.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ""
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}
