# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output_ShiTuV1_bnneck/
  device: gpu
  save_interval: 120
  eval_during_train: True
  eval_interval: 1
  epochs: 100
  print_batch_step: 20
  use_visualdl: False
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference_ShiTuV1_bnneck
  eval_mode: retrieval
  use_dali: True
  use_dali_eval: False
  # used for static mode and model export
  to_static: False

# model architecture
Arch:
  name: RecModel
  infer_output_key: features
  infer_add_softmax: False

  Backbone:
    name: PPLCNet_x2_5
    pretrained: True
    use_ssld: True
    class_num: &feat_dim 512
  Neck:
    name: BNNeck
    num_features: *feat_dim
    weight_attr:
      initializer:
        name: Constant
        value: 1.0
    bias_attr:
      initializer:
        name: Constant
        value: 0.0
      learning_rate: 1.0e-20 # NOTE: Temporarily set lr small enough to freeze the bias to zero
  Head:
    name: ArcMargin
    embedding_size: 512
    class_num: 185341
    margin: 0.2
    scale: 30

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.04
    warmup_epoch: 5
  regularizer:
    name: "L2"
    coeff: 0.00001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: /workspace/dongshuilong/dataset/ppshitu_traindata/
      cls_label_path: /workspace/dongshuilong/dataset/ppshitu_traindata/train_reg_all_data.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ""

    sampler:
      name: DistributedBatchSampler
      batch_size: 256
      drop_last: False
      shuffle: True
    loader:
      num_workers: 16
      use_shared_memory: True

  Eval:
    Query:
      dataset:
        name: VeriWild
        image_root: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/
        cls_label_path: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/val_list.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ""
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 8
        use_shared_memory: True

    Gallery:
      dataset:
        name: VeriWild
        image_root: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/
        cls_label_path: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/val_list.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ""
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 8
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}
