# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./outputs_traindataset_v2_all/baseline_shitu_triplet_emb512_no_RE_rotate90_lr0.06_lcnetv2_cv2_nolastconv_dropout_bigv2_idsampler_ratio_traindatasetv2_whole_taml"
  device: "gpu"
  save_interval: 120
  eval_during_train: True
  eval_interval: 1
  epochs: 100
  print_batch_step: 20
  use_visualdl: False
  eval_mode: "retrieval"
  retrieval_feature_from: "features" # 'backbone' or 'features'
  re_ranking: False
  use_dali: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: "./inference_baseline_shitu_triplet_emb512_no_RE_rotate90_lr0.06_lcnetv2_cv2_nolastconv_dropout_bigv2__idsampler_ratio_taml"

AMP:
  scale_loss: 65536
  use_dynamic_loss_scaling: True
  # O1: mixed fp16
  level: O1

# model architecture
Arch:
  name: RecModel
  infer_output_key: features
  infer_add_softmax: False

  Backbone:
    name: PPLCNetV2_base
    use_ssld: True
    pretrained: True
    last_stride: 1
    use_last_conv: False
    fc_dropout: True
    dropout_prob: 0.2
    class_num: &feat_dim 512
  Neck:
    name: BNNeck
    num_features: *feat_dim
    weight_attr:
      initializer:
        name: Constant
        value: 1.0
    bias_attr:
      initializer:
        name: Constant
        value: 0.0
      learning_rate: 1.0e-20 # NOTE: Temporarily set lr small enough to freeze the bias to zero
  Head:
    name: "FC"
    embedding_size: *feat_dim
    class_num: &class_num 192612
    weight_attr:
      initializer:
        name: Normal
        std: 0.001
    bias_attr: False

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
    - TripletAngleMarinLoss:
        weight: 1.0
        margin: 0.5
        reduction: mean
        add_absolute: True
        absolute_loss_weight: 0.1
        normalize_feature: True
        feature_from: "features"
        ap_value: 0.8
        an_value: 0.4
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  - Momentum:
      scope: RecModel
      momentum: 0.9
      lr:
        name: Cosine
        learning_rate: 0.06 # 8gpux256bs
        warmup_epoch: 5
      regularizer:
        name: "L2"
        coeff: 0.00001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: "ImageNetDataset_cv2"
      image_root: /workspace/dongshuilong/dataset/ppshitu_traindata/
      cls_label_path: /workspace/dongshuilong/dataset/ppshitu_traindata/train_reg_all_data_v2.txt
      backend: "cv2"
      relabel: True
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: [224, 224]
            return_numpy: False
            interpolation: "bilinear"
            backend: "cv2"
        - RandFlipImage:
            flip_code: 1
        - Pad_cv2:
            padding: 10
        - RandCropImageV2:
            size: [224, 224]
        - RandomRotation:
            prob: 0.5
            degrees: 90
            interpolation: "bilinear"
        - ResizeImage:
            size: [224, 224]
            return_numpy: False
            interpolation: "bilinear"
            backend: "cv2"
        - ToCHWImage: {}
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    sampler:
      name: PKSampler
      batch_size: 256
      sample_per_id: 4
      drop_last: False
      shuffle: True
      sample_method: "id_avg_prob"
      id_list: [50030, 80700, 92019, 96015] 
      ratio: [4, 4]
    loader:
      num_workers: 16
      use_shared_memory: True
  Eval:
    Query:
      dataset:
        name: VeriWild_New_cv2
        image_root: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/
        cls_label_path: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/val_list.txt
        backend: "cv2"
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [224, 224]
              return_numpy: False
              interpolation: "bilinear"
              backend: "cv2"
          - ToCHWImage: {}
          - NormalizeImage:
              scale: 1.0/255.0
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 8
        use_shared_memory: True

    Gallery:
      dataset:
        name: VeriWild_New_cv2
        image_root: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/
        cls_label_path: /workspace/dongshuilong/dataset/ppshitu_traindata/Aliproduct/val_list.txt
        backend: "cv2"
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [224, 224]
              return_numpy: False
              interpolation: "bilinear"
              backend: "cv2"
          - ToCHWImage: {}
          - NormalizeImage:
              scale: 1.0/255.0
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 8
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}
